---
- name: Install remote facts
  hosts: webserver
  vars:
    remote_dir: /etc/ansible/facts.d
    facts_file: custom.fact
  tasks:
    - name: Delete the remote directory
      file:
        path: "{{ remote_dir }}"
        state: absent


# restore_playbook.yml
# ---
# - name: Restore playbook.yml 
#   hosts: all 
#   tasks: 
#     - name: 팩트 삭제 - /etc/ansible/facts.d/* 
#       file: 
#         path: /etc/ansible/facts.d
#         state: absent 
#     - name: 패키지 삭제 - httpd
#       yum: 
#         name: httpd 
#         state: absent 