---
- name: Install remote facts
  hosts: webserver
  vars:
    remote_dir: /etc/ansible/facts.d
    facts_file: custom.fact
  tasks:
    - name: Create the remote directory
      file:
        state: directory
        recurse: yes
        path: "{{ remote_dir }}"
    - name: Install the new facts
      copy:
        src: "{{ facts_file }}"
        dest: "{{ remote_dir }}"
    
# ---
# - name: 원격 호스트 사용자 정의 팩트 파일 배포
#   hosts: webserver 
#   tasks: 
#     - name: 디렉토리 생성 -/etc/ansible/facts.d 
#       file: 
#         path: /etc/ansible/facts.d
#         state: directory 
#         mode: '0755'
#     - name: 파일 복사 - /etc/ansible/facts.d/custon.fact
#       copy: 
#         src: custom.fact 
#         dest: /etc/ansible/facts.d/custom.fact  