---
- name: create user account for web2
  hosts: web2.example.com
  become: true
  remote_user: ansible
  vars_files:
    - secret2.yml
  tasks:
    - name: Create user from secret.yml
      # useradd user01
      # passwd user01
      user:
        name: "{{ username }}"
        password: "{{ pwhash|password_hash('sha512') }}"
        