---
  - name: 방화벽 패키지 설치 
    yum:
      name: "{{ firewall_pkg }}"
      state: latest

  - name: 방화벽 스타트
    service:
      name: "{{ firewall_svc }}"
      enabled: true
      state: started

  - name: 방화벽 웹 포트 등록 {{ rule }}
    firewalld:
      service: "{{ item }}"
      immediate: true
      permanent: true
      state: enabled
    with_items: "{{ rule }}"
    
