---
- name: 디렉토리 생성 예제
  hosts: fileservers
  tasks:
    - name: 변수 include
      include_vars: paths.yml

    - name: 디렉토리 생성
      file:
        path: "{{ paths.fileserver }}"
        state: directory
        mode: 0755
      register: output
      
    - name: 디버깅
      debug:
        var: output

# ---
# - name: Configure fileservers
#   hosts: fileservers
#   tasks:
#     - name: Imports the variables file
#       include_vars: paths.yml

#     - name: Creates the remote directory
#       file:
#         path: "{{ paths.fileserver }}"
#         state: directory
#         mode: 0755
#       register: result

#     - name: Debugs the results
#       debug:
#         var: result
