---
- name: 파일 배포 
  hosts: dev
  tasks:
    - name: /etc/myhost 파일 배포 
      template:
        src: templates/hosts.j2
        dest: /etc/myhosts
        owner: root
        group: root
        mode: '0644'