- name: Restore the web server
  hosts: web1.example.com
  tasks:
    # 1. 방화벽에 서비스 제거 (http, https)
      - name: Close the service ports - http, https
        firewalld:
          service: "{{ item }}"
          permanent: yes
          state: disabled
          immediate: yes
        loop:
          - http
          - https

    # 2. 파일 삭제 /var/www/html/index.html
      - name: Remove a file - /var/www/html/index.html
        file:
          path: /var/www/html/index.html
          state: absent
        
    # 3. 패키지 삭제 httpd, mod_ssl
      - name: Remove the packages - httpd, mod_ssl
        yum:
          name:
            - httpd
            - mod_ssl
          state: absent
