---
# tasks file for roles/apache
  # 1. 패키지 설치 - httpd, firewalld 
- name: 패키지 설치 - httpd, mod_ssl, firewalld
  yum: 
    name:
      - httpd
      - mod_ssl
      - firewalld
    state: present
  # 2. 서비스 설정 - /var/www/html/hello.html
- name: 서비스 설정  - /var/www/html/index.html
  template:
    src: templates/index.html.j2
    dest: /var/www/html/index.html
    
  # 3. 서비스 기동 - httpd, firewalld 
- name: 서비스 기동 - httpd, firewalld
  service:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  loop:
    - httpd
    - firewalld
 # 4. 방화벽 서비스 포트 등록 - http,https 
- name: 방화벽 서비스 포트 등록  - http, https
  firewalld:
    service: "{{ item }}"
    zone: public
    permanent: yes
    immediate: yes
    state: enabled
  loop:
    - http
    - https
