---
- name: Install and start Apache HTTPD
  hosts: webservers
  tasks:
    # 1. 패키지 설치
    # 2. 서비스 설정
    # 3. 서비스 기동
    # 4. 방화벽 등록
    # 5. SELinux 설정

    # 1. 패키지 설치
    # yum install httpd mod_ssl
    - name: Install the packages - httpd
      yum:
        name: httpd
        state: latest

    # 2. 서비스 설정
    # files/index.html -> web#:/var/www/html/index.html
    - name: Copy file from files/index.html to /var/www/html/index.html
      copy:
        src: files/index.html
        dest: /var/www/html/index.html

    # 3. 서비스 기동
    #systemctl enable --now httpd
    - name: Enable or Start the service - httpd.service
      service:
        name: httpd
        state: started
        enabled: yes

    # 4. 방화벽 등록
    # firewall-cmd --permanent --add-service=http
    # firewall-cmd --reload
    - name: Resister with firewall service - http
      firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: true


    # 5. SELinux 설정
