---
- name: 웹-DB 패키지 설치 - {{ ansible_local.custom.packages.db_package }}, {{ ansible_local.custom.packages.web_package }}
  yum: 
    name:
      - "{{ ansible_local.custom.packages.db_package }}"
      - "{{ ansible_local.custom.packages.web_package }}"
    state: latest

- name: DB 서비스 기동
  service:
    name: "{{ ansible_local.custom.services.db_service }}"
    state: started
    enabled: yes

- name: 웹 서비스 기동
  service:
    name: "{{ ansible_local.custom.services.web_service }}" 
    state: started
    enabled: yes