---
- name: DB install and Service start
  hosts: databases
  tasks:
    # DB install
    - name: MariaDB install
      yum:
        name:
          - mariadb-server
          - python3-PyMySQL
        state: latest
      notify:
        - set db password

    # -> DB PW

    # DB Service start
    - name: MariaDB 서비스 기동
      service:
        name: mariadb
        state: started
        enabled: yes

    # config file change
    - name: DB 설정 파일 교체
      get_url:
        url: 'http://192.168.10.10/my.cnf.standard'
        dest: /etc/my.cnf
        owner: root
        group: root
        mode: '0644'
        force: yes
      notify:
        - restart db service

  # handler
  handlers:
    - name: set db password
      mysql_user:
        name: root
        password: soldesk1.

    - name: restart db service
      service:
        name: mariadb
        state: restarted


# --------------------------------------------------

# ---
# - name: MariaDB server is installed
#   hosts: databases
#   vars:
#     db_packages:
#       - mariadb-server
#       - python3-PyMySQL
#     db_service: mariadb
#     resources_url: http://ansible.example.com
#     config_file_url: "{{ resources_url }}/my.cnf.standard"
#     config_file_dst: /etc/my.cnf
#   tasks:
#     - name: "{{ db_packages }} packages are installed"
#       yum:
#         name: "{{ db_packages }}"
#         state: present
#       notify:
#         - set db password

#     - name: Make sure the database service is running
#       service:
#         name: "{{ db_service }}"
#         state: started
#         enabled: true

#     - name: The {{ config_file_dst }} file has been installed
#       get_url:
#         url: "{{ config_file_url }}"
#         dest: "{{ config_file_dst }}"
#         owner: mysql
#         group: mysql
#         force: yes
#       notify:
#         - restart db service

#   handlers:
#     - name: restart db service
#       service:
#         name: "{{ db_service }}"
#         state: restarted

#     - name: set db password
#       mysql_user:
#         name: root
#         password: soldesk1.
